import { describe, expect, it } from "vitest";
import { buildSnapshotObjectKey } from "./kv-key-utils";

// Expected literals generated by the lovablehtml worker's derivation
// (deriveSnapshotObjectKey). If a case fails, the two repos derive different
// keys for the same page — fix the drift, never the fixture.
// The www/apex pair MUST produce the same key (host normalization), and the
// tracking-param URL must hash identically to its stripped form.
const FIXTURES: Array<[string, string]> = [
  ["https://www.example.com/about", "v1/example.com/about_abf24d57a306f5a7.html"],
  ["https://example.com/about", "v1/example.com/about_abf24d57a306f5a7.html"],
  [
    "https://concerly.lovable.app/venue/bessie-hall-sapporo",
    "v1/concerly.lovable.app/venue_bessie-hall-sapporo_e3d1d30f62818e37.html",
  ],
  ["https://example.com/", "v1/example.com/root_f06d5a21feba0fdd.html"],
  [
    "https://sub.example.com/products?b=2&a=1",
    "v1/sub.example.com/products_6386b93c627b6a30.html",
  ],
  [
    "https://example.com/products?a=1&b=2&utm_source=x&_ga=123",
    "v1/example.com/products_dea9c3d5840ae46b.html",
  ],
];

describe("snapshot object key parity with lovablehtml worker", () => {
  it.each(FIXTURES)("derives the worker's key for %s", async (url, expected) => {
    expect(await buildSnapshotObjectKey({ targetUrl: url })).toBe(expected);
  });

  it("collapses www and apex to one key", async () => {
    expect(
      await buildSnapshotObjectKey({ targetUrl: "https://www.example.com/about" }),
    ).toBe(
      await buildSnapshotObjectKey({ targetUrl: "https://example.com/about" }),
    );
  });

  it("collapses trailing-slash variants to one key", async () => {
    expect(
      await buildSnapshotObjectKey({
        targetUrl: "https://example.com/about/",
      }),
    ).toBe("v1/example.com/about_abf24d57a306f5a7.html");
  });

  it("ignores tracking params in the key", async () => {
    expect(
      await buildSnapshotObjectKey({
        targetUrl: "https://example.com/products?a=1&b=2&utm_source=x&_ga=123",
      }),
    ).toBe(
      await buildSnapshotObjectKey({
        targetUrl: "https://example.com/products?b=2&a=1",
      }),
    );
  });
});
